<table>
    <thead>
    <tr>
        <th>key</th>
        <th>name</th>
        <th>provider</th>
        <th>description</th>
        <th>unit</th>
        <th>cost</th>
    </tr>
    </thead>
    <tbody>
    @foreach($products as $product)
        <tr>
            <td>{{$product->key}}</td>
            <td>{{$product->name}}</td>
            <td>{{$product->provider}}</td>
            <td>{{$product->description}}</td>
            <td>{{$product->unit}}</td>
            <td>{{$product->cost}}</td>
        </tr>
    @endforeach
    </tbody>
</table>